Add bm25 service
primeqa/primeqa pull request #402
Opened 2022-12-12 20:05 UTC by bhavani105

# Pull Request      

- Implement BM25 (Pyserini) Retriever and Reader component
- Add support for BM25 indexing and retrieval in the services layer

```Closes #(issue)```       

Notes:
- Replace `(issue)` **above** ↑↑↑ with the issue this PR closes to automatically link the two.
This must be done when the PR is created.
- Add multiple `Closes #(issue)` as needed.
- If this PR is work towards but does not close an issue, simply tag the issue without mentioning `Closes`.

## Description

**Describe** the changes proposed by this PR below to give the reviewer context below ↓↓↓

```(description)```     

### Request Review

Be sure to **request a review** from one or more reviewers (unless the PR is to an unprotected branch).

## Versioning

When opening a PR to make changes to PrimeQA (i.e. `primeqa/`) master, be sure to increment the version following
[semantic versioning](https://semver.org/).  The VERSION is stored [here](https://github.com/primeqa/primeqa/blob/main/VERSION) 
and is incremented using `bump2version {patch,minor,major}` as described in the (development guide documentation)[development.html].

 - [ ] Have you updated the VERSION?
 - [ ] Or does this PR not change the `primeqa` package or was not into master?

After pulling in changes from master to an existing PR, ensure the VERSION is updated appropriately.
This may require bumping the version again if it has been previously bumped.

If you're not quite ready yet to post a PR for review, feel free to open a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/).

## Releases

### After Merging
If merging into master and VERSION was updated, after this PR is merged:
- [ ] [Create a release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release) from the master with version equal to [VERSION](https://github.com/primeqa/primeqa/blob/main/VERSION)
- [ ] Not merging to master or VERSION not updated

### Checklist

Review the following and mark as completed:
- [ ] [Tag an issue or issues](#what-does-this-pr-do) this PR addresses.
- [ ] Added [description](#description) of changes proposed.
- [ ] Review requested as [appropriate](#request-review).
- [ ] Version bumped as [appropriate](#Versioning).
- [ ] New classes, methods, and functions documented.
- [ ] Documentation for modified code is updated.
- [ ] Built documentation to confirm it renders as expected (see [here](development.md)).
- [ ] Code cleaned up and commented out code removed.
- [ ] Tests added to ensure all functionalities tested at >= 60% unit test coverage (see [here](development.md)).
- [ ] Code cleaned up and commented out code removed.
- [ ] Release created [as needed](#after-merging) after merging.

2022-12-14 18:22 UTC, kpfadnis requested changes
@bhavani105 Please verify that `retrieve` signature change is fixed across all retrievers and necessary notebooks as well. Thanks

2022-12-14 18:22 UTC, kpfadnis commented on primeqa/pipelines/components/base.py
> +    def retrieve(self, queries: List[str], *args, **kwargs):
If we are changing signature of `retrieve` method, we need to follow that signature change in both `sparse` and `dense` retrievers.

2022-12-14 18:22 UTC, kpfadnis commented on primeqa/pipelines/components/retriever/sparse.py
> +        qids = [str(idx) for  idx, query in enumerate(input_texts) ]
Shouldn't this change to `queries` as per change in the `base.py` for `retriever` component?

2022-12-14 22:26 UTC, kpfadnis approved these changes
LGTM. Nice work!

2022-12-14 23:10 UTC, franzmpub commented on primeqa/pipelines/components/indexer/dense.py
> +
How about other dense IR engines?

2022-12-14 23:12 UTC, franzmpub commented on primeqa/pipelines/components/indexer/sparse.py
> +    def get_engine_type(self) -> str:
Similarly as with dense IR (but more hypothetically): how about other sparse IR engines?

2022-12-14 23:52 UTC, franzmpub approved these changes
LGTM

2022-12-15 16:42 UTC, hrojek approved these changes
Tested end to end, with primeqa-ui and primeqa-orchestrator.

2022-12-15 19:07 UTC, merged