Lfqa demo
primeqa/primeqa pull request #472
Opened 2023-03-20 20:20 UTC by seirasto

# Pull Request      

## What does this PR do?

Add generative capabilities to PrimeQA UI (FiD and FlanT5)

2023-03-21 15:36 UTC, hrojek approved these changes
LGTM

2023-03-22 14:00 UTC, kpfadnis requested changes
@seirasto Left few comments. I see one or two major blockers and few minor fixes.

2023-03-22 19:04 UTC, bhavani105 reviewed
Have all 3 readers been tested end to end
Is there REST support for GenerativeReader and PromptReader

2023-03-23 03:29 UTC, seirasto commented on primeqa/components/reader/generative.py
> +        predictions = {}
It is twice. Removing one.

2023-03-23 03:33 UTC, seirasto commented on primeqa/components/reader/prompt.py
> +    def __hash__(self) -> int:
removing duplicate hash in BamReader (rest is good)

2023-03-23 03:57 UTC, seirasto commented on primeqa/components/reader/prompt.py
> +        pass
added

2023-03-23 03:59 UTC, seirasto commented on primeqa/components/reader/prompt.py
>                  sys.exit(0)
Modified to return None

2023-03-23 04:00 UTC, seirasto commented on primeqa/services/grpc_server/reader_service.py
> +                    else:
This is the current setup that works for everything. All readers other than extractive are generative.

2023-03-23 04:16 UTC, kpfadnis approved these changes
Nice job. LGTM.

2023-03-23 12:43 UTC, bhavani105 approved these changes
LGTM

2023-03-27 21:45 UTC, merged